name = "DataSkimmer"
uuid = "54a5dec1-bae8-447e-bd66-474f7865e6c6"
authors = ["Hannes <hasnep@gmail.com>"]
version = "0.1.0"

[deps]
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
Tables = "1.1"
PrettyTables = "0.9"
StructArrays = "0.4"
julia = "1"
